**AMB2162-PALLAVI_P_BHAT**

In [ ]:
import pandas as pd
production = pd.Series(
         [30,60,45,25],
         index=["wheat","rice","maize","barley"]
)
print(production)

wheat     30
rice      60
maize     45
barley    25
dtype: int64

In [ ]:
import pandas as pd
production = pd.Series([30,60,45,25],index=["wheat","rice","maize","barley"])
print(production)

wheat     30
rice      60
maize     45
barley    25
dtype: int64

In [ ]:
#by crop name label
print(production["rice"])
print(production.loc["rice"]) #location by label
print(production.iloc[2]) # location by indexing
print(production.sum())
print(production.mean())
print(production.max())
print(production.idxmax()) #maximum production crop
# it prints the index label of the maximum value in the series

60
60
45
160
40.0
60
rice

In [ ]:
# crops with production greater than 40 tons
high_production=production[production>40] # inner one gives true or false , outer variable production
# is used for name of that
print(high_production)
print()# for space

print(production>40)

rice     60
maize    45
dtype: int64

wheat     False
rice       True
maize      True
barley    False
dtype: bool

In [ ]:
# loc means label based indexing

In [ ]:
import pandas as pd
df=pd.DataFrame({
    "name":["akhil","bobby","charan"],
    "age":[25,30,35],
    "city":["ny","la","chicago"]

},index=["a","b","c"])

print(df)
print()
print(df.loc["b"])

     name  age     city
a   akhil   25       ny
b   bobby   30       la
c  charan   35  chicago

name    bobby
age        30
city       la
Name: b, dtype: object

In [ ]:
print(df)
print()
print(df.loc[["a","c"],["name","city"]])

     name  age     city
a   akhil   25       ny
b   bobby   30       la
c  charan   35  chicago

     name     city
a   akhil       ny
c  charan  chicago

In [ ]:
print(df.iloc[[0,2]])

     name  age     city
a   akhil   25       ny
c  charan   35  chicago

In [ ]:
# a data frame is a two dimentional data structure.a table like excel sheet -made of multiple series
import pandas as pd
data={
    "Farm":["farm a","farm b","farm c","farm d"],
     "crop":["wheat","rice","maize","redgram"],
    "area_hectares":[10,14,12,3],
    "production_tons":[12,22,31,7]
}

df=pd.DataFrame(data)
print(df)
df.head(2) # to get top 2
df.tail(2) # bottom row

     Farm     crop  area_hectares  production_tons
0  farm a    wheat             10               12
1  farm b     rice             14               22
2  farm c    maize             12               31
3  farm d  redgram              3                7

     Farm     crop  area_hectares  production_tons
2  farm c    maize             12               31
3  farm d  redgram              3                7

In [ ]:
df.head(2)

     Farm   crop  area_hectares  production_tons
0  farm a  wheat             10               12
1  farm b   rice             14               22

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Farm             4 non-null      object
 1   crop             4 non-null      object
 2   area_hectares    4 non-null      int64
 3   production_tons  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

In [ ]:
df.describe() #summary statistics

       area_hectares  production_tons
count       4.000000         4.000000
mean        9.750000        18.000000
std         4.787136        10.677078
min         3.000000         7.000000
25%         8.250000        10.750000
50%        11.000000        17.000000
75%        12.500000        24.250000
max        14.000000        31.000000

In [ ]:
#add a new coloumn to existing one
df['new_coloumn_name']=df["production_tons"]/df["area_hectares"]
print(df)
#data frame is permanently changed

     Farm     crop  area_hectares  production_tons  new_coloumn_name
0  farm a    wheat             10               12          1.200000
1  farm b     rice             14               22          1.571429
2  farm c    maize             12               31          2.583333
3  farm d  redgram              3                7          2.333333

In [ ]:
#display only farm d and farm d
df.iloc[[1,3]]

     Farm     crop  area_hectares  production_tons  new_coloumn_name
1  farm b     rice             14               22          1.571429
3  farm d  redgram              3                7          2.333333

In [ ]:
df.iloc[[1,3],[0,1,2]]

     Farm     crop  area_hectares
1  farm b     rice             14
3  farm d  redgram              3

In [ ]:
#slicing of the coloumn
df.iloc

In [ ]:
#filter data
#farms growing wheat
print(df["crop"]=="wheat")
print()
wheat_farms=df[df["crop"]=="wheat"]
print(wheat_farms)

0     True
1    False
2    False
3    False
Name: crop, dtype: bool

     Farm   crop  area_hectares  production_tons  new_coloumn_name
0  farm a  wheat             10               12               1.2

In [ ]:
# sort farms by high production
sorted_df=df.sort_values(by="production_tons",ascending=False)
print(sorted_df)

     Farm     crop  area_hectares  production_tons  new_coloumn_name
2  farm c    maize             12               31          2.583333
1  farm b     rice             14               22          1.571429
0  farm a    wheat             10               12          1.200000
3  farm d  redgram              3                7          2.333333

In [ ]:
#group by operation
avg_yield=df.groupby("crop")["new_coloumn_name"].sum()
print(avg_yield)

crop
maize      2.583333
redgram    2.333333
rice       1.571429
wheat      1.200000
Name: new_coloumn_name, dtype: float64